### ISSUE TITLE
 The  pre-trained weight link you gave cannot be downloaded

### ISSUE THREAD

**Issue by ZZXin** [MedChaabane/DEFT#1]
Hi, thanks for your awesome job, I  am reproducing your code. But the pre-trained weight link you gave requires permission to access. Could  you open the permission on the Google cloud disk?

**Comment by MedChaabane** [comment]
Hi ,
Thanks for your interest in our code. I believe that with the link on GitHub anyone can download the models. Can you try again with this link: https://drive.google.com/drive/folders/1dlVoV-4fMYlttdj2ba0unn6WX-nxaC48?usp=sharing. If it didn't work for you, please send me an e-mail and I will send the models to you.
Thanks,

Thanks,

**Comment by ZZXin** [comment]
yes，it works，I can download it， thanks a lot.
