### ISSUE TITLE
Changing the backbone 

### ISSUE THREAD

**Issue by HilmiiKumdakci** [MedChaabane/DEFT#5]
How should I make this change? I could not find any part which consists YOLO bakcbone.

**Comment by MedChaabane** [comment]
Hi, the current code supports only CenterNet detector. We will try to have a better version of the code that supports multiple detectors. However for now, if you have YOLO detector, you can add the appearance feature extractor (https://github.com/MedChaabane/DEFT/blob/main/src/lib/model/networks/AFE.py) and add matching loss in your training following our train code (https://github.com/MedChaabane/DEFT/blob/main/src/lib/trainer.py) and in that way you can convert it to a tracker as well.

**Comment by Catchen98** [comment]
如何将追踪模块用于mmdetection中呢，例如faster rcnn
