### ISSUE TITLE
How to train on COCO/own dataset?

### ISSUE THREAD

**Issue by Hiddenfire21** [MedChaabane/DEFT#8]
First off, I would like to say thank you for sharing this amazing work.
Will you be adding instructions or scripts to train and test on own dataset?

Is it correct to say the dataset should be a COCO like format with the inclusion of track_id in the annotation?

**Comment by Hiddenfire21** [comment]
Some debugging indicates that img_ids is empty due to this condition 
                and abs(img_info["frame_id"] - frame_id) > 0
in 
    def _load_pre_data_AFE(self, video_id, frame_id, sensor_id=1):
        img_infos = self.video_to_images[video_id]

        if "train" in self.split:
            img_ids = [
                (img_info["id"], img_info["frame_id"])
                for img_info in img_infos
                if abs(img_info["frame_id"] - frame_id) <= self.opt.max_frame_dist_AFE
                and abs(img_info["frame_id"] - frame_id) > 0
                and (
                    not ("sensor_id" in img_info) or img_info["sensor_id"] == sensor_id
                )
            ]

**Comment by MedChaabane** [comment]
yes we have plans to add scripts to train and test on your own dataset but if you have dataset in coco format you can modify the current code to make it work for your own dataset with no much work I think.
