### ISSUE TITLE
trajectory_dataset.py issues when training on MOT17

### ISSUE THREAD

**Issue by simon-rob** [MedChaabane/DEFT#9]
I have noticed a couple of issues:

1. The Dataloader  ( _load_data, _load_image_anns) is internally loading images (` img = cv2.imread(img_path)`) which are  never used in the `__getitem__` function therefore dramatically increasing the overhead of the Dataloader.

2. No bounding boxes are being returned by `__getitem__`  and the Dataloader is eventually terminated with a recursion depth error because _get_bboxes    `cls_id > self.opt.num_classes` is **True** due  to **num_classes** not being set in opts.py Adding  --"num_classes 1"  to  mot17_tracking.sh solves this.  i.e` python train_prediction.py tracking --exp_id mot17_motion_model --dataset mot --dataset_version 17trainval --gpus 0 --num_classes 1`

**Comment by MedChaabane** [comment]
thanks for your comments. we will check if num_classes 1 is required in MOT17 training.
